-- Simulated Data Warehouse: the asset the tool analyses.
--
-- This is the *real* Postgres counterpart of the hand-authored catalog in
-- `src/dcra/evidence/dataset.py`. When a database is configured, the collector
-- nodes read column metadata and dependencies straight from `information_schema`
-- / `pg_catalog` against this schema (see `dcra.evidence.warehouse`). Downstream
-- *usage* (reads/day per consumer) is not a database fact and stays synthetic.
--
-- Loaded by: deploy/init-db.sh, the docker-compose init mount, and `make dw`.
-- Idempotent.

CREATE SCHEMA IF NOT EXISTS reporting;

CREATE TABLE IF NOT EXISTS orders (
    id                 bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id        bigint       NOT NULL,
    customer_legacy_id varchar(32),
    status             varchar(16)  NOT NULL DEFAULT 'NEW',
    notes_internal     text
);

CREATE TABLE IF NOT EXISTS order_items (
    id       bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint      NOT NULL,
    sku      varchar(32) NOT NULL,
    qty      integer     NOT NULL DEFAULT 1,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id)
);

-- Lineage: views under `reporting` that depend on orders columns.
CREATE OR REPLACE VIEW reporting.v_customer_orders AS
    SELECT id AS order_id, customer_id, customer_legacy_id, status
    FROM orders;

CREATE OR REPLACE VIEW reporting.v_legacy_bridge AS
    SELECT DISTINCT customer_legacy_id
    FROM orders
    WHERE customer_legacy_id IS NOT NULL;

CREATE OR REPLACE VIEW reporting.v_open_orders AS
    SELECT id AS order_id, customer_id, status
    FROM orders
    WHERE status IN ('NEW', 'PAID');

-- ---------------------------------------------------------------------------
-- Seed. ~30 curated rows (shown first in the app's table view) + a bulk pad
-- so `pg_class.reltuples` / row_estimate reads as a real table after ANALYZE.
-- Re-runnable: clears its own rows first.
-- ---------------------------------------------------------------------------
TRUNCATE order_items, orders RESTART IDENTITY;

INSERT INTO orders (id, customer_id, customer_legacy_id, status, notes_internal) OVERRIDING SYSTEM VALUE VALUES
    ( 1, 10293, 'LGC-0007742', 'DELIVERED', NULL),
    ( 2, 11841, NULL,          'PAID',      'Cliente pediu antecipação do envio.'),
    ( 3, 10022, 'LGC-0003118', 'SHIPPED',   NULL),
    ( 4, 12507, NULL,          'NEW',       NULL),
    ( 5, 10293, 'LGC-0007742', 'CANCELLED', 'Cancelado a pedido do cliente (SAC #8821).'),
    ( 6, 11310, 'LGC-0009004', 'DELIVERED', NULL),
    ( 7, 13288, NULL,          'PAID',      NULL),
    ( 8, 10761, 'LGC-0002251', 'REFUNDED',  'Produto com defeito; reembolso total.'),
    ( 9, 12044, 'LGC-0006689', 'SHIPPED',   NULL),
    (10, 11987, NULL,          'DELIVERED', NULL),
    (11, 10450, 'LGC-0001120', 'NEW',       'Endereço corrigido pelo SAC.'),
    (12, 12903, 'LGC-0008337', 'PAID',      NULL),
    (13, 11102, NULL,          'SHIPPED',   NULL),
    (14, 10293, 'LGC-0007742', 'DELIVERED', NULL),
    (15, 13571, 'LGC-0010885', 'CANCELLED', 'Pagamento não confirmado em 48h.'),
    (16, 10088, 'LGC-0004410', 'DELIVERED', NULL),
    (17, 12765, NULL,          'PAID',      NULL),
    (18, 11529, 'LGC-0005907', 'NEW',       NULL),
    (19, 13004, 'LGC-0002884', 'SHIPPED',   'Frete grátis aplicado (campanha).'),
    (20, 10640, NULL,          'DELIVERED', NULL),
    (21, 12218, 'LGC-0007063', 'PAID',      NULL),
    (22, 11876, 'LGC-0009915', 'CANCELLED', 'Estoque insuficiente no CD de origem.'),
    (23, 10399, NULL,          'DELIVERED', NULL),
    (24, 13322, 'LGC-0001547', 'SHIPPED',   NULL),
    (25, 11045, 'LGC-0006228', 'PAID',      NULL),
    (26, 12960, NULL,          'NEW',       NULL),
    (27, 10714, 'LGC-0008801', 'DELIVERED', NULL),
    (28, 11683, 'LGC-0003370', 'REFUNDED',  'Divergência de cor; reembolso parcial.'),
    (29, 12471, NULL,          'SHIPPED',   NULL),
    (30, 10902, 'LGC-0005134', 'DELIVERED', NULL);

-- explicit ids above don't advance the identity sequence; realign it before bulk insert
SELECT setval(pg_get_serial_sequence('orders', 'id'), (SELECT max(id) FROM orders));

INSERT INTO orders (customer_id, customer_legacy_id, status)
SELECT
    1000 + (random() * 5000)::int,
    CASE WHEN random() < 0.30 THEN NULL
         ELSE 'LGC-' || lpad(((random() * 99999)::int)::text, 7, '0') END,
    (ARRAY['NEW','PAID','SHIPPED','DELIVERED','CANCELLED','REFUNDED'])[floor(random() * 6 + 1)]
FROM generate_series(1, 3000);

INSERT INTO order_items (order_id, sku, qty)
SELECT
    o.id,
    'SKU-' || lpad(((random() * 999)::int)::text, 4, '0'),
    1 + (random() * 3)::int
FROM orders o, generate_series(1, 2) g
WHERE o.id <= 200;

ANALYZE orders;
ANALYZE order_items;
